### ISSUE TITLE
serenityCucumberVersion not assigned

### ISSUE THREAD

**Issue by Coada** [serenity-bdd/serenity-junit-starter#1]
Hello,

commit 8b423c6 seems to have removed assignment of `serenityCucumberVersion` in `libraries.gradle`. Gradle can later not resolve the variable a bit further down when it is used, which prevented me from getting all the necessary dependencies.

I am a bit amazed that it has not been detected since the change, but probably there hasn't been anyone who has imported the starter project via Gradle since?

I solved the issue by adding `serenityCucumberVersion = '1.9.19'`.

**Comment by wakaleo** [comment]
Fixed - the cucumber dependency is not required for this project.
