### ISSUE TITLE
HTTPS needed for bintray-plugins in pom.xml

### ISSUE THREAD

**Issue by fkurzyk** [serenity-bdd/serenity-junit-starter#11]
In pom.xml, bintray-plugins's url is using HTTP, while the site apparently stopped supporting it in Jan 2020 and returns HTTP 403 now:

> `> mvn clean
[INFO] Scanning for projects...
[INFO]
[INFO] -----------< net.serenitybdd.starter:serenity-junit-starter >-----------
[INFO] Building Sample Serenity BDD project using JUnit 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: http://jcenter.bintray.com/org/apache/maven/plugins/maven-failsafe-plugin/2.22.1/maven-failsafe-plugin-2.22.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.034 s
[INFO] Finished at: 2020-02-09T04:33:41+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-failsafe-plugin:2.22.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-failsafe-plugin:jar:2.22.1: Could not transfer artifact org.apache.maven.plugins:maven-failsafe-plugin:pom:2.22.1 from/to central (http://jcenter.bintray.com): Authorization failed for http://jcenter.bintray.com/org/apache/maven/plugins/maven-failsafe-plugin/2.22.1/maven-failsafe-plugin-2.22.1.pom 403 Forbidden -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

This needs to be changed to https://jcenter.bintray.com.

**Comment by wakaleo** [comment]
Thanks for pointing this out, it should be now fixed.
