### ISSUE TITLE
SerenityRunner not working with Junit5

### ISSUE THREAD

**Issue by divisathyan** [serenity-bdd/serenity-junit-starter#16]
We have migrated our code to use JUnit5 and have a functional test, which Serenity runs and generates a report.
With JUnit5, the report html/csv is not generated

**Comment by wakaleo** [comment]
You need to run it as a JUnit 4 legacy test, as Serenity doesn't natively support JUnit 5.

**Comment by divisathyan** [comment]
Thank you for the confirmation
