### ISSUE TITLE
Build failing with error "Could not get unknown property 'logbackVersion'"

### ISSUE THREAD

**Issue by u-sandeep** [serenity-bdd/serenity-junit-starter#32]
A problem occurred evaluating root project 'serenity-junit-starter'.
> Could not get unknown property 'logbackVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by wakaleo** [comment]
Not much to go on there I'm afraid

**Comment by u-sandeep** [comment]
the error was in a build.gradle file as 'logBackVersion' variable was not defined
